*&---------------------------------------------------------------------*
*&  Include           ZQMI_UP_CHANGE_GRADE_TOP
*&---------------------------------------------------------------------*
TABLES : MSEG,ZBATCHISTORY,MCHA.

********DATA FOR HISTORY
DATA : BEGIN OF IZBATCHISTORY OCCURS 0." IT_HISTORY OCCURS 0.
        INCLUDE STRUCTURE ZBATCHISTORY.
DATA: GRDT1(30),
      TYPE(30),
      LENGHT(20),
      WIDTH(20),
      WEIGHT(20),
      GRDT2(30),
*      NLENGHT(20),
*      NCHARG LIKE MSEG-CHARG,
*      NWEIGHT(20),
      CHK TYPE C LENGTH 1.
DATA : END OF IZBATCHISTORY. "IT_HISTORY.

**********DATA FOR CHANGE GRADE
DATA : BEGIN OF IT_MCHB  OCCURS 0 .
        INCLUDE STRUCTURE MCHB.
DATA : END OF IT_MCHB.

DATA : BEGIN OF IT_CHANGE OCCURS 0 ,
        MATNR LIKE MCHB-MATNR,
        WERKS LIKE MCHB-WERKS,
        LGORT LIKE MCHB-LGORT,
        TYPE TYPE C LENGTH 30,
        LENGHT TYPE C LENGTH 30,
        WIDTH TYPE C LENGTH 30,
        WEIGHT TYPE C LENGTH 30,
        NOROLA TYPE C LENGTH 30,
        NOROLB TYPE C LENGTH 30,
        BATCHA LIKE MCHB-CHARG,
        GRADEA TYPE C LENGTH 30,
        CRITA TYPE C LENGTH 30,
        GRADEB TYPE C LENGTH 30,
        CRITB TYPE C LENGTH 30,
        NMEMO TYPE C LENGTH 18,
        AUTHOR TYPE C LENGTH 30,
        RSLOC LIKE MCHB-LGORT,
        DGRADE TYPE C LENGTH 30,
        DGRADE2 TYPE C LENGTH 30,
        DCRITA TYPE C LENGTH 30,
        DCRITB TYPE C LENGTH 30,
        GPMNG LIKE ZBATCHISTORY-GPMNG,
        MEINS LIKE ZBATCHISTORY-MEINS,
        BOX(1),
        CHK(1) TYPE C,
        VENUM LIKE VEPO-VENUM,
        UNVEL LIKE VEPO-UNVEL,
        EXIDV LIKE VEKP-EXIDV,
        UEVEL LIKE VEKP-UEVEL,
        MAGRV LIKE VEKP-MAGRV,
        SPRNT LIKE ZBATCHISTORY-SPRNT,
        NCHARG LIKE MCHB-CHARG,
        EXLENG TYPE C LENGTH 5,
        STATUSEXLENG TYPE STRING,
        STATUSKUPAS TYPE STRING,
        LOGEXLENG TYPE STRING,
        LOGKUPAS TYPE STRING,
        LOGEXLENGCANCEL TYPE STRING,
        LOGKUPASCANCEL TYPE STRING,
        POKUPAS LIKE MSEG-AUFNR,
        POAJDS LIKE MSEG-AUFNR,
        STATUS(40) TYPE C,
        INDC(40) TYPE C,
        LINE_COLOR(4) TYPE C,
        WC TYPE C.
DATA : END OF IT_CHANGE.
DATA : BEGIN OF IT_REPORT OCCURS 0,
    ZNOT(16),
    ZDOC TYPE MSEG-MBLNR,
    ZMAT TYPE MSEG-MATNR,
    ZBAT TYPE MSEG-CHARG,
    ZSTA TYPE BDCMSGCOLL-MSGTYP,
    ZTEX(300),
    CELLCOLOR TYPE LVC_T_SCOL.
DATA:  END OF IT_REPORT.
***DATA FOR CHECK BATCH IN HU
DATA: BEGIN OF IT_HU OCCURS 0,
      EXIDV LIKE VEKP-EXIDV,
      CHARG LIKE VEPO-CHARG,
      VENUM LIKE VEPO-VENUM,
      UNVEL LIKE VEPO-UNVEL,
      OCHARG LIKE VEPO-CHARG.
DATA: END OF IT_HU.

DATA :V_TYPE TYPE C,
      WA_CHANGE LIKE IT_CHANGE,
      WA_HISTORY LIKE ZBATCHISTORY,
      O_MSGNO TYPE SY-MSGNO,
      O_MSGV1 TYPE SY-MSGV1,
      O_MSGV2 TYPE SY-MSGV2,
      O_MSGV3 TYPE SY-MSGV3,
      O_MSGV4 TYPE SY-MSGV4,
      OPT LIKE CTU_PARAMS,
      MSG TYPE I,
      VENUM TYPE I,
      VEPO TYPE I,
      INDEX TYPE I,
      DSTATUS TYPE C,
      LSEQ TYPE I VALUE 0,
      U_CHANGE LIKE STANDARD TABLE OF IT_CHANGE WITH HEADER LINE,
      U_HU LIKE STANDARD TABLE OF IT_CHANGE WITH HEADER LINE,
      IT_BDCDATA    LIKE BDCDATA OCCURS 0 WITH HEADER LINE,
      IT_BDCMSGCOLL LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
      TBATCH LIKE STANDARD TABLE OF CLBATCH WITH HEADER LINE,
      REPORT LIKE STANDARD TABLE OF IT_REPORT WITH HEADER LINE,
      IT_GRADE LIKE STANDARD TABLE OF VTENTRIES WITH HEADER LINE,
      LS_REF1 TYPE REF TO CL_GUI_ALV_GRID,
      IT_CRITERIA LIKE STANDARD TABLE OF VTENTRIES WITH HEADER LINE.

DATA : ZCLBATCH LIKE STANDARD TABLE OF CLBATCH WITH HEADER LINE,
       ZCHAR LIKE STANDARD TABLE OF BAPI1003_ALLOC_VALUES_CHAR WITH HEADER LINE,
       IT_MSEG LIKE STANDARD TABLE OF MSEG WITH HEADER LINE,
       DEL_MSEG LIKE STANDARD TABLE OF MSEG WITH HEADER LINE,
       WA_MSEG LIKE MSEG,
       ZBRETURN LIKE STANDARD TABLE OF BAPIRET2 WITH HEADER LINE.

******data for get roll no.
DATA : BEGIN OF NOROLL OCCURS 0,
        MATNR LIKE MCHB-MATNR,
        BATCHA LIKE MCHB-CHARG,
        WERKS LIKE MCHB-WERKS,
        LGORT LIKE MCHB-LGORT,
        ROLL TYPE C LENGTH 40.
DATA : END OF NOROLL.
DATA : TCHARG LIKE MSEG-CHARG,
       V_MATNR LIKE MCH1-MATNR.
DATA : BEGIN OF IT_NIK OCCURS 0,
        OBJID LIKE HRP1001-OBJID,
END OF IT_NIK.
"TABLE FOR F4 HELP
DATA : BEGIN OF ITHELP OCCURS 0,
          WERKS LIKE ZTMAP_SLOCRR-WERKS,
          LGORT LIKE T001L-LGORT,"ZTMAP_SLOCRR-ZRRLGORT,
          LGOBE LIKE T001L-LGOBE,
       END OF ITHELP.
DATA : BEGIN OF LMSG OCCURS 0,
          MSGID  LIKE SY-MSGID,
          MSGTY  LIKE SY-MSGTY,
          MSGNO  LIKE SY-MSGNO,
          MSGV1  LIKE SY-MSGV1,
          MSGV2  LIKE SY-MSGV2,
          MSGV3  LIKE SY-MSGV3,
          MSGV4  LIKE SY-MSGV4,
          LINENO TYPE MESG-ZEILE,
        END OF LMSG.

DATA:    V_DYNINDEX TYPE SY-STEPL,
      FLAG TYPE C,
      REPID TYPE SYREPID.
DATA: V_PROG LIKE ZPROGINFO-PGMNA VALUE 'ZQMI_SR_INS'.

DATA :PLNNR LIKE QALS-PLNNR,
      PLNAL LIKE QALS-PLNAL,
      ARBID LIKE PLPO-ARBID,
      OBJID LIKE CRHD-OBJID,
      HROID LIKE CRHD-HROID,
      NIK LIKE HRP1001-OBJID,
      MESG(80),
      ARBPL LIKE CRHD-ARBPL,
      ATINN LIKE CAWN-ATINN,
      TEMP TYPE C LENGTH 10,
      MSG1 TYPE C  LENGTH 200,
      MSG2 TYPE C  LENGTH 200,
      MSG3 TYPE C  LENGTH 200,
      DBTYPE TYPE DBCON_DBMS.
*data for pop up.
DATA: EXLENG TYPE C LENGTH 5,
*        EXLENG TYPE ZEXLENG,
        RETURNCODE(1) TYPE C.
DATA: BEGIN OF IT_SOPOP OCCURS 0.
        INCLUDE STRUCTURE SVAL.
DATA: END OF IT_SOPOP.

SELECTION-SCREEN BEGIN OF BLOCK X3 WITH FRAME TITLE H01.
PARAMETERS: PIL1 RADIOBUTTON GROUP RAD1.
SELECTION-SCREEN SKIP.
SELECT-OPTIONS: P_WERKS FOR MSEG-WERKS.
SELECT-OPTIONS: P_LGORT FOR MSEG-LGORT.
SELECT-OPTIONS: P_BUDAT FOR ZBATCHISTORY-BUDAT.
SELECT-OPTIONS: P_CHARG FOR MCHA-CHARG.
SELECT-OPTIONS: P_UNAME FOR ZBATCHISTORY-UNAME.
SELECT-OPTIONS: P_NMEMO FOR ZBATCHISTORY-NMEMO.
SELECTION-SCREEN SKIP 2.

PARAMETERS: PIL2 RADIOBUTTON GROUP RAD1 DEFAULT 'X'.
SELECTION-SCREEN SKIP.
SELECT-OPTIONS: P_CHARG2 FOR MCHA-CHARG NO INTERVALS.
PARAMETERS: P_LGORT2 LIKE MSEG-LGORT,
            P_AUTH2 LIKE ZBATCHISTORY-AUTHR,
            P_NMEMO2 LIKE ZBATCHISTORY-NMEMO,
            P_GRADE2 LIKE ZBATCHISTORY-GRADE.
SELECTION-SCREEN END OF BLOCK X3.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-002.
PARAMETERS: S_CONN LIKE MSEG-SGTXT   MODIF ID CON.
SELECTION-SCREEN END OF BLOCK BLOCK2.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK3 WITH FRAME TITLE TEXT-003.
PARAMETERS: P1 RADIOBUTTON GROUP GRP1 USER-COMMAND AC,
            P2 RADIOBUTTON GROUP GRP1 DEFAULT 'X'.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN PUSHBUTTON /12(79) INFO USER-COMMAND INFO.
SELECTION-SCREEN END OF BLOCK BLOCK3.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TCHANGE' ITSELF
CONTROLS: TCHANGE TYPE TABLEVIEW USING SCREEN 0200.

*&SPWIZARD: LINES OF TABLECONTROL 'TCHANGE'
DATA:     G_TCHANGE_LINES  LIKE SY-LOOPC.

DATA:     OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TPOP' ITSELF
CONTROLS: TPOP TYPE TABLEVIEW USING SCREEN 0300.

*&SPWIZARD: LINES OF TABLECONTROL 'TPOP'
DATA:     G_TPOP_LINES  LIKE SY-LOOPC.

*--------------------------------------------------------------------*
*UNTUK WARNA IJO DAN MERAH
*--------------------------------------------------------------------*
CONSTANTS : GCF_E1(4) TYPE C VALUE '@0A@',
            GCF_W1(4) TYPE C VALUE '@09@',
            GCF_S1(4) TYPE C VALUE '@08@'.

DATA : IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
       IT_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA:LV_I TYPE I,
     LV_C(1) TYPE C,
     LV_DOUBL(1) TYPE C,
     LV_COLOR(4) TYPE C.

DATA: FLAGLOOPEXLENG TYPE STRING.